### ISSUE TITLE
JSX support?

### ISSUE THREAD

**Issue by treshugart** [mrjoelkemp/node-detective-es6#3]
I'm currently using this project in [Galvatron](https://github.com/treshugart/galvatron) and one of the issues I'm running into is that I want to parse JavaScript that contains JSX.

I can't transform the JSX prior to running it through this because whoever is using Galvatron for tracing most likely doesn't yet know all of the files they need to transform. 

This may really be an issue for your dependency project [node-source-walk](https://github.com/mrjoelkemp/node-source-walk) that uses [acorn](https://github.com/marijnh/acorn) directly who seem to have a way of [supporting JSX](https://github.com/RReverser/acorn-jsx) (referenced from the [acorn project page here](https://github.com/marijnh/acorn#plugins)).

Thoughts?

**Comment by mrjoelkemp** [comment]
Thanks for the request! I've been thinking about using babel's parser to avoid parsing errors due to new syntax. 

If you'd like to submit a PR to source walk adding jsx support, I'd gladly cut a release.

**Comment by treshugart** [comment]
Awesome, I'll have a look at it a bit later and see what I can do. I'll close this and open an issue there.

**Comment by mrjoelkemp** [comment]
Haven't looked into hoe to configure acorn to support jsx, but you can
supply options to the Walker constructor that get passed through to acorn.
If that works, then the fix could be in this lib.
