### ISSUE TITLE
Should support export x from './module' syntax

### ISSUE THREAD

**Issue by olalonde** [mrjoelkemp/node-detective-es6#7]
See https://github.com/babel/babylon/blob/master/ast/spec.md#exportnameddeclaration and 
https://github.com/babel/babylon/blob/master/ast/spec.md#exportalldeclaration.

Related issue: https://github.com/pahen/madge/issues/89

**Comment by olalonde** [comment]
Sent a PR https://github.com/mrjoelkemp/node-detective-es6/pull/8

**Comment by mrjoelkemp** [comment]
Fixed via #8
